config/routes.rb
Rails.application.routes.draw do
  resources :cards

  

end

app/models/card.rb
class Card < ActiveRecord::Base
	#each card is assigned to one person
	belongs_to :people

	#function that searches for cards based on the card number
	def self.search(search)
	  if search
	    where('number LIKE ?', "%#{search}%")
	  else
	    where(nil)
	  end
	end

end

app/models/people.rb
class People < ActiveRecord::Base
	#a person can be assigned to many cards
	has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction 

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.search(params[:search]).order(sort_column + " " + sort_direction)
  end



  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:number, :expirationDate, :dateReceived, :active, :inTransitTo, :transferActive, :people_id)
    end

     def sort_column
       params[:sort] || "number"
     end
     
     def sort_direction
       params[:direction] || "asc"
     end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(column, title = nil)
	    title ||= column.titleize
	    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
	    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
	    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	  end
	
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards.html.erb
<div class="row">
  <% @cards.each do |card| %>
    <div class="col-md-4">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <% if card.active %>
          <div class="panel-heading" role="tab" id="headingOne">
            <% else %>
            <div class="panel-heading grey" role="tab" id="headingOne">
            <% end %>
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= card.id %>" aria-expanded="true" aria-controls="collapseOne"><h3 class="panel-title"><%= card.number %><span class="arrow pull-right"><i class="fa fa-chevron-circle-down"></i></span><span class="arrow pull-right"><i class="fa fa-chevron-circle-up hidden"></i></span></h3></a>
          </div>
          <ul class="list-group-collapse collapse" id="collapse<%= card.id %>" role="tabpanel" aria-labelledby="headingOne">
            <li class="list-group-item"><em>Valid Thru</em> <%= card.expirationDate.strftime("%b %d, %Y") %></li>
            <li class="list-group-item"><em>Date Received</em> <%= card.expirationDate.strftime("%b %d, %Y") %></li>
            <li class="list-group-item light-purple">
              <i class="fa fa-gift fa-fw"></i>&nbsp;&nbsp; <%= best_in_place card, :people_id, :as => :select, :collection => People.all.map { |i| [i.id, i.name] }, :nil => 'Give this card to someone?' %>
            </li>

            <% if card.active %>
              <li class="list-group-item default"><i class="fa fa-plus-circle fa-fw"></i>&nbsp;&nbsp;
            <% else %>
              <li class="list-group-item default red"><i class="fa fa-times-circle fa-fw"></i>&nbsp;&nbsp;
            <% end %>
                <%= best_in_place card, :active, as: :checkbox, collection: {false: "This card is disbaled. Activate it?", true: "This card is active. Disable it?"}, :classes => 'highlight_on_success' %>
              </li>
            
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('.highlight_on_success').bind("ajax:success", function(){$(this).closest('li').toggleClass('red');$(this).closest('panel-heading').toggleClass('grey')});
  $('.name').bind("ajax:success", function(){$(this).closest('i').append('<em>In transit to</em>');});
  $(document).ready(function(){    
      $(".panel-title").on('click', function () {
         $(this).children().children().first().toggleClass("hidden");
         $(this).children().children().eq(1).toggleClass("hidden")
      });

      // $('.panel-title').on('click', function () {
      //    $(this).children().children().removeClass("fa fa-chevron-circle-up").addClass("fa fa-chevron-circle-down");
      // });
  });

</script>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :expirationDate %><br>
    <%= f.date_select :expirationDate %>
  </div>
  <div class="field">
    <%= f.label :dateReceived %><br>
    <%= f.date_select :dateReceived %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Cards I Own</h1>
    </div>
    <div class="col-md-3">
      <div class="btn-group pull-right margins hidden-xs" role="group" aria-label="...">
        <button type="button" id="expand" class="btn btn-default">Collapse All</button>
      </div>
    </div>
  </div>
  <div class="row">
    
    <div class="col-md-12">
      <%= form_tag cards_path, :method => 'get', :id => "cards_search", :class => "" do %>
        <p>
          <form class="form-search">
              <div class="input-group">
                  <%= text_field_tag  :search, params[:search], :class => "col-md-12 form-control" %>
                  <span class="input-group-btn">
                      <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                  </span>
              </div>
          </form>
         


        </p>

      </div>
    </div>
    <div class="row padded">
      <div class="col-md-12">

        <div class="btn-group btn-group-justified" role="group" aria-label="...">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default"><%= sortable "number" %></button>
          </div>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default"><%= sortable "expirationDate","Exp Date" %></button>
          </div>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default"><%= sortable "dateReceived", "Receive Date" %></button>
          </div>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default"><%= sortable "active" %></button>
          </div>
        </div>

      </div>
    </div>
    <div id="cards"><%= render 'cards' %></div>
  <% end %>
    
  
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @card.number %>
</p>

<p>
  <strong>Expirationdate:</strong>
  <%= @card.expirationDate %>
</p>

<p>
  <strong>Datereceived:</strong>
  <%= @card.dateReceived %>
</p>

<p>
  <strong>Active:</strong>
  <%= @card.active %>
</p>

<p>
  <strong>Intransitto:</strong>
  <%= @card.inTransitTo %>
</p>

<p>
  <strong>Transferactive:</strong>
  <%= @card.transferActive %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WePay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Lato:400,400italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">UPMC</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#">Cards I Own <span class="sr-only">(current)</span></a></li>
	      </ul>

	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<%= yield %>

</body>
</html>